version: '3'
services:
  orion-ld:
    image: 'quay.io/fiware/orion-ld@sha256:a65adbface4d5467add735d01c7204951e3c474ef8fc901fbd3a2af285beafea'
    restart: always
    environment:
      ORIONLD_MONGO_HOST: 'mongodb'
      ORIONLD_MONGO_USER: 'admin'
      ORIONLD_MONGO_PASSWORD: 'password'
      ORIONLD_TROE: 'TRUE'
      ORIONLD_TROE_USER: 'orion'
      ORIONLD_TROE_PWD: 'orion'
      ORIONLD_TROE_HOST: 'timescale'
      ORIONLD_LOG_FOR_HUMANS: 'TRUE'
      ORIONLD_DISABLE_FILE_LOG: 'TRUE'
    depends_on:
      - mongodb
    ports:
      - '8082:1026'
  timescale:
    image: timescaledev/timescaledb-ha:pg14-multi-all
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U orion" ]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 10s
    environment:
      POSTGRES_USER: 'orion'
      POSTGRES_PASSWORD: 'orion'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - "5432"

  mongodb:
    image: mongo:5
    healthcheck:
      test: ["CMD-SHELL", "mongo", "--port", "27017", "-u", "admin", "-p", "password", "--eval", "\"db.adminCommand('ping')\""]
      interval: 5s
      timeout: 1s
      retries: 12
      start_period: 10s
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'admin'
      MONGO_INITDB_ROOT_PASSWORD: 'password'
    ports:
      - '27017'
    command: --nojournal --quiet
    volumes:
      - mongo-db:/data

  mongo-express:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: 'mongodb'
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_AUTH_DATABASE: 'admin'
      ME_CONFIG_MONGODB_ADMINUSERNAME: 'admin'
      ME_CONFIG_MONGODB_ADMINPASSWORD: 'password'
      ME_CONFIG_BASICAUTH_USERNAME: ''
    depends_on:
      orion-ld:
        condition: service_healthy
    ports:
      - '8183:8081'

  postgresqls:
    container_name: "postgresqlpostgis"
    image: "postgis/postgis"
    ports:
      - "5433:5432"
    volumes:
       - db_persdata:/var/lib/postgrespers
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: geodata_cip
    networks:
      - default

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: info@masarinconsulting.se
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  mongo-db: ~
  db_persdata : {}
  pgadmin-data:
